language: node_js

sudo: required

matrix:
  include:
    - os: linux
      node_js: 
       - 10
       - 14

before_install:
  #- sudo apt-get update
  - sudo apt-get install gobjc++
  - npm i -g prebuild
  # install cmake
  - wget http://www.cmake.org/files/v3.16/cmake-3.16.0.tar.gz
  - tar -xf cmake-3.16.0.tar.gz
  - cd cmake-3.16.0/
  - ./configure
  - make
  - cd ..
  - cmake --version
